const db = require("../config/db");

const normalizePriority = (priority) => {
  const value = String(priority || "").trim().toLowerCase();
  if (value === "emergency") return "Emergency";
  if (value === "urgent") return "Urgent";
  return "Normal";
};

const validateAppointmentData = ({ patientId, doctorId, appointmentDate, appointmentTime, reason, priority }) => {
  if (!patientId) return "Patient is required.";
  if (!doctorId) return "Doctor is required.";
  if (!appointmentDate) return "Appointment date is required.";
  if (!appointmentTime) return "Appointment time is required.";
  if (!reason || !reason.trim()) return "Reason for appointment is required.";
  if (!priority) return "Priority is required.";

  const normalizedPriority = normalizePriority(priority);
  if (!["Emergency", "Urgent", "Normal"].includes(normalizedPriority)) {
    return "Priority must be Emergency, Urgent, or Normal.";
  }

  return null;
};

// POST - Book Appointment (appointment table only; no token auto-creation)
// Token is generated by receptionist upon patient check-in
exports.bookAppointment = (req, res) => {
  const { patientId, doctorId, appointmentDate, appointmentTime, reason, priority } = req.body;
  const validationError = validateAppointmentData({ patientId, doctorId, appointmentDate, appointmentTime, reason, priority });

  if (validationError) {
    return res.status(400).json({ message: validationError });
  }

  const parsedPatientId = parseInt(patientId, 10);
  const parsedDoctorId = parseInt(doctorId, 10);

  if (isNaN(parsedPatientId) || parsedPatientId <= 0) {
    return res.status(400).json({ message: "Valid patient ID is required." });
  }

  if (isNaN(parsedDoctorId) || parsedDoctorId <= 0) {
    return res.status(400).json({ message: "Valid doctor ID is required." });
  }

  const patientQuery = "SELECT patientId FROM patient WHERE patientId = ?";
  db.query(patientQuery, [parsedPatientId], (err, patientRows) => {
    if (err) {
      return res.status(500).json({ message: "Database error validating patient", error: err.message });
    }

    if (patientRows.length === 0) {
      return res.status(404).json({ message: "Patient not found." });
    }

    const doctorQuery = "SELECT doctorId FROM doctor WHERE doctorId = ?";
    db.query(doctorQuery, [parsedDoctorId], (err, doctorRows) => {
      if (err) {
        return res.status(500).json({ message: "Database error validating doctor", error: err.message });
      }

      if (doctorRows.length === 0) {
        return res.status(404).json({ message: "Doctor not found." });
      }

      const appointmentQuery = "INSERT INTO appointment (patientId, doctorId, appointmentDate, appointmentTime, reason, status) VALUES (?, ?, ?, ?, ?, 'Booked')";
      db.query(appointmentQuery, [parsedPatientId, parsedDoctorId, appointmentDate, appointmentTime, reason], (err, appointmentResult) => {
        if (err) {
          return res.status(500).json({ message: "Appointment booking failed", error: err.message });
        }

        res.status(201).json({
          message: "Appointment booked successfully",
          appointment: {
            appointmentId: appointmentResult.insertId,
            patientId: parsedPatientId,
            doctorId: parsedDoctorId,
            appointmentDate,
            appointmentTime,
            reason,
            status: "Booked",
          },
        });
      });
    });
  });
};

// GET - View All Appointments
exports.getAllAppointments = (req, res) => {
  const query = `
    SELECT a.appointmentId, p.name AS patientName, d.doctorName,
           a.appointmentDate, a.appointmentTime, a.status, a.reason
    FROM appointment a
    JOIN patient p ON a.patientId = p.patientId
    JOIN doctor d ON a.doctorId = d.doctorId
    ORDER BY a.appointmentId DESC
  `;

  db.query(query, (err, result) => {
    if (err) {
      return res.status(500).json({ message: "Error fetching appointments", error: err.message });
    }

    res.status(200).json({
      message: "Appointments fetched successfully",
      appointments: result,
    });
  });
};

const updateAppointmentStatus = (appointmentId, status, res, successMessage) => {
  const query = "UPDATE appointment SET status = ? WHERE appointmentId = ?";

  db.query(query, [status, appointmentId], (err, result) => {
    if (err) {
      return res.status(500).json({ message: `Error updating appointment status to ${status}`, error: err.message });
    }

    if (result.affectedRows === 0) {
      return res.status(404).json({ message: "Appointment not found" });
    }

    res.status(200).json({ message: successMessage, appointmentId, status });
  });
};

// PUT - Cancel Appointment
exports.cancelAppointment = (req, res) => {
  const appointmentId = req.params.id;
  updateAppointmentStatus(appointmentId, "Cancelled", res, "Appointment cancelled successfully");
};

// PUT - Complete Appointment
exports.completeAppointment = (req, res) => {
  const appointmentId = req.params.id;
  updateAppointmentStatus(appointmentId, "Completed", res, "Appointment marked as completed");
};
